// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:todo_firebase/keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidOptions;
      case TargetPlatform.iOS:
        return iosOptions;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidOptions = FirebaseOptions(
    apiKey: FirebaseKeys.androidApiKey,
    appId: FirebaseKeys.androidAppId,
    messagingSenderId: FirebaseKeys.androidMessagingSenderId,
    projectId: FirebaseKeys.androidProjectId,
    storageBucket: FirebaseKeys.androidStorageBucket,
  );

  static const FirebaseOptions iosOptions = FirebaseOptions(
    apiKey: FirebaseKeys.iosApiKey,
    appId: FirebaseKeys.iosAppId,
    messagingSenderId: FirebaseKeys.iosMessagingSenderId,
    projectId: FirebaseKeys.iosProjectId,
    storageBucket: FirebaseKeys.iosStorageBucket,
    iosBundleId: FirebaseKeys.iosBundleId,
  );
}
